name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
          
      - name: Build
        run: |
          cd cmd/zehd
          go build -o zehd ./...
          cd ../../
          echo "VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
          echo "$(cat ./CHANGELOG)" > changelog.txt
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: zehd
          path: cmd/zehd/zehd
          
      - name: Upload Changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: changelog.txt
          
      - name: Set Outputs
        id: vars
        run: echo "::set-output name=version::$(cat ./VERSION)"
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: zehd
          
      - name: Download Changelog
        uses: actions/download-artifact@v2
        with:
          name: changelog
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          artifacts: 'zehd/zehd' 
          tag: v${{ needs.build.outputs.version }}
          name: ZEHD v${{ needs.build.outputs.version }}
          body_path: changelog.txt
          allowUpdates: true
