name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Build
        run: |
          cd cmd/frontend-microservice
          go build ./...
          mv ./frontend-microservice ./zehd
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          artifacts: 'zehd'
          tag: v$(cat VERSION)
          release_name: ZEHD $(cat VERSION)
          body: $(cat CHANGELOG)

