name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Set Environment Variables
        run: |
          echo "v$(cat VERSION)" >> $GITHUB_ENV
          cat CHANGELOG >> $GITHUB_ENV    
      - name: Build
        run: |
          cd cmd/frontend-microservice
          go build ./...
          mv ./frontend-microservice ./zehd
          cd ../..
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          artifacts: 'zehd'
          tag: ${{ env.VERSION }}
          name: ZEHD ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}