name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
          
      - name: Build
        run: |
          cd cmd/zehd
          go build ./...
          cd ../..
          echo "VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
          echo "CHANGELOG=`$(cat ./CHANGELOG)`" >> $GITHUB_ENV
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          artifacts: 'zehd'
          tag: v${{ env.VERSION }}
          name: ZEHD v${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
