name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build
        run: |
          cd cmd/zehd
          go build -o zehd ./...
          cd ../../
          
      - name: Set Version
        id: vars
        run: echo "version=$(cat ./VERSION)" >> $GITHUB_OUTPUT
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zehd
          path: cmd/zehd/zehd
          
      - name: Upload Changelog
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: CHANGELOG
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: zehd
          
      - name: Download Changelog
        uses: actions/download-artifact@v3
        with:
          name: changelog
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: 'zehd'
          tag: v${{ needs.build.outputs.version }}
          name: ZEHD v${{ needs.build.outputs.version }}
          bodyFile: CHANGELOG
          allowUpdates: true
